name: taskflow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_messaging: ^16.0.1
  google_sign_in: ^7.1.1
  sqflite: ^2.4.2
  path: ^1.9.1
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  injectable_generator: ^2.8.1
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/i18n/itaskflowicon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/en.json
    - assets/i18n/hi.json
    - assets/i18n/itaskflowicon.jpeg
