// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9MMCGBU_f5frTQlDUntOCDNdFufeXvLY',
    appId: '1:743847539480:web:a5bcf61a03a994c656e46d',
    messagingSenderId: '743847539480',
    projectId: 'taskflow-app-dce48',
    authDomain: 'taskflow-app-dce48.firebaseapp.com',
    storageBucket: 'taskflow-app-dce48.firebasestorage.app',
    measurementId: 'G-NYND7F3QGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKMwnO44e45BFVQuQe78ScIDykqLeik9k',
    appId: '1:743847539480:android:d5c6dbb48932b15456e46d',
    messagingSenderId: '743847539480',
    projectId: 'taskflow-app-dce48',
    storageBucket: 'taskflow-app-dce48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtFj8H8n8KxMcGqwq6Z8c3fB7sHUidnYc',
    appId: '1:743847539480:ios:7bac41476f57ddea56e46d',
    messagingSenderId: '743847539480',
    projectId: 'taskflow-app-dce48',
    storageBucket: 'taskflow-app-dce48.firebasestorage.app',
    iosBundleId: 'com.example.taskflowApp',
  );
}
